### ISSUE TITLE
Hot-changing To-Do List

### ISSUE THREAD

**Issue by JackyJnirvana** [JackyWangMislantiaJnirvana/Minecraft-Classic-164-Modpack#3]
- Install Cores and tools
- [x] Chicken bone core
- [ ] CoFH Core
- [x] Not Enough Items
- [x] Walia
- [x] NEI addons
- [ ] ????
- Install the three MJs
- [x] Buildcraft
- [x] Forestry
- [x] Railcraft
- Install MJ add-ons
- [x] Binnie mods
- [x] BC Tools
- [ ] QuarryPlus
- [ ] ?
- Install IC² and addons
- [x] IndustryCraft²
- Install EU add-ons
- [ ] NuclearControl
- [ ] LevelStorage
- [ ] ?
- Install Magical mods
- [ ] Thaumcraft
- [ ] ArsMagic
- [ ]
  Botania
- [ ] 
- Install Magical add-ons
- [ ] 
- [ ] 
- [ ] 
- Install AE
- [x] AppliedEnergy
- Install AE add-ons
- [x] ExtraCells
- Install Project.Red
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- Install RIM
- [ ] RedstoneInMotion
- [ ] resourcepack (because this mod's look is **awful!**)
- Install FZ
- [ ] Factorization
  *Install GT
- [ ] GregTech 4.08s
- Install computer mods
- [ ] OpenComputer
- [ ] ComputerCraft
- Misc
- [ ] ArmorStatusHUD
- [ ] IronChest
- [ ] 

**[Under Construction]**

**Comment by panda2134** [comment]
i'll install fz as quickly as i can,because i have time now XD

**Comment by panda2134** [comment]
i found a typo and corrected it ;)

**Comment by JackyJnirvana** [comment]
@panda2134 
FZ? OK, open a new branch based on master and name it "deve#5_install_FZ"
er, typo? what is that = =
The electricity booooooom just now... so I didn't see the message that time. sorry for that!

**Comment by panda2134** [comment]
2016-01-26 21:45 GMT+08:00 JackyWangMislantiaJnirvana <
notifications@github.com>:

> # 

hacen't -> hasn't
XD
[image: 内嵌图片 1]
so slow...

**Comment by JackyJnirvana** [comment]
@panda2134 
2₃³₃³₃³₃³₃³₃ , assigned me 66666
interesting
